crudexample/crudexample/urls.py
from django.contrib import admin
from django.urls import path
from employee import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Crud route
    path('emp', views.emp),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

crudexample/employee/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    # Kolom kolom dibawah ini akan menjadi kolom di database
    # dan selain itu akan menjadi kolom di form secara otomatis
    
    # Buat kolom eid
    eid = models.CharField(max_length=20)
    
    # Buat kolom ename
    ename = models.CharField(max_length=100)
    
    # Buat kolom eemail
    eemail = models.EmailField(max_length=100)
    
    # Buat kolom econtact
    econtact = models.CharField(max_length=20)
    
    # Informasi meta tentang tabel
    class Meta:
        
        # Nama tabel yang akan dibuat
        db_table = 'employee'

crudexample/employee/forms.py
# Import form libarary
from dataclasses import field
from django import forms

# Import Employee model
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

crudexample/employee/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
import employee  
from employee.forms import EmployeeForm  
from employee.models import Employee  

# Create your views here.

# Store data if method is POST
# and show form if method is GET
def emp(request):
    # Jika metode POST
    if request.method == "POST" :
        # Tangkap semua request
        form = EmployeeForm(request.POST)
        
        # dan jika form valid
        if form.is_valid():
            try:
                # Simpan data
                form.save()
                
                # Redirect ke show
                return redirect('/show')
            except:
                pass
    else: 
            # Jika metode GET maka buat form kosong
            # berdasarkan model Employee
            form = EmployeeForm()
    return render(request, 'index.html', {'form':form})
        
# Show all employees data    
def show(request):
    employees = Employee.objects.all()
    return render(request, 'show.html', {'employees':employees})

# Edit an employee data by id
def edit(request, id):
    # employee = Employee.objects.get(id=id)
    employee = get_object_or_404(Employee, id=id)
    
    return render(request, 'edit.html', {'employee':employee})

def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    
    if form.is_valid():
        form.save()
        return redirect('/show')
    
    return render(request, 'edit.html', {'employee': employee})

# Destroy data by id
def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect('/show')

crudexample/employee/templates/edit.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Index</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>
  <form method="POST" class="post-form" action="/update/{{employee.id}}">
    {% csrf_token %}
    <div class="container">
      <br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Update Details</h3>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Id:</label>
        <div class="col-sm-4">
          <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label>
        <div class="col-sm-4">
          <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">
          <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Contact:</label>
        <div class="col-sm-4">
          <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-success">Update</button>
        </div>
      </div>
    </div>
  </form>
</body>

</html>

crudexample/employee/templates/index.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Index</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>
  {% comment %} 
    Pada file index.html ini terdapat fungsi auto generate form
    yang diambil dari model, dengan bantuan dari file forms.py
  {% endcomment %}

  <form method="POST" class="post-form" action="/emp">
    {% csrf_token %}
    <div class="container">
      <br>
      <div class="form-group">
        <h3>Enter Details</h3>
      </div>
      {% comment %} <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Id:</label>
        <div class="col-sm-4">
          {{ form.eid }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label>
        <div class="col-sm-4">
          {{ form.ename }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">
          {{ form.eemail }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Contact:</label>
        <div class="col-sm-4">
          {{ form.econtact }}
        </div>
      </div> {% endcomment %}
      {% comment %} atau bisa juga seperti ini {% endcomment %}

      {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
      {% endfor %}
      
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>

    </div>
  </form>
</body>

</html>

crudexample/employee/templates/show.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>

    
    <div class="container">
        <h4>
            Employee
        </h4>
        <br>
        <table class="table table-striped table-bordered table-sm">
            <thead class="thead-dark">
                <tr>
                    <th>Employee ID</th>
                    <th>Employee Name</th>
                    <th>Employee Email</th>
                    <th>Employee Contact</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td>{{ employee.eid }}</td>
                    <td>{{ employee.ename }}</td>
                    <td>{{ employee.eemail }}</td>
                    <td>{{ employee.econtact }}</td>
                    <td>
                        <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
                        <a href="/delete/{{ employee.id }}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
    <br>
    <br>
    <center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
</body>

</html>